# Destroy a resource group

- name: Delete "{{resource_group_name}}" Resource Group
  azure_rm_resourcegroup:
    name: "{{resource_group_name}}"
    state: absent
    force: yes

- name: Webhook Notification to Teams for Destruction
  delegate_to: localhost
  uri:
    body: "{\"text\": \"Resource Group {{resource_group_name}} and all its contents were destroyed!\"}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: no
