# azure_net specific parameters

# use parent_parameters.yml for secure variables (ansible-vault)

#module parameters
virtual_network_name: "{{resource_group_name}}-virtual-network"
virtual_network_address_prefix: "10.128.0.0/16"
managemenet_subnet: "management"
management_address_prefix_cidr: "10.128.1.0/24"
external_subnet: "external"
external_address_prefix_cidr: "10.128.10.0/24"
internal_subnet: "internal"
internal_address_prefix_cidr: "10.128.20.0/24"
