# Destroy all Services in this solution

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    password: "{{BIGIPadminPassword}}"
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    validate_certs: no
  delegate_to: localhost

- name: Get Bigip Authentication Token from {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigip_auth_token: "{{ bigip_auth_response.json.token.token }}"

- name: Destroy All Services in AS3 on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: DELETE
    status_code: 200
    url: "https://{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com/mgmt/shared/appsvcs/declare"
    validate_certs: no

- name: Destroy Service2 from f5.http iApp on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_iapp_service:
    name: Service2
    password: "{{BIGIPadminPassword}}"
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    state: absent
    user: "{{BIGIPadminUsername}}"
    validate_certs: no
  delegate_to: localhost

- name: Destroy Service node {{application_server_name}} leftover from AS3 and iApp's
  bigip_node:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    password: "{{BIGIPadminPassword}}"
    validate_certs: false
    state: absent
    partition: Common
    name: 10.128.20.4
  delegate_to: localhost

- name: Destroy Service1 virtual server "Service1_vs" on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_virtual_server:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: absent
    name: Service1_vs
    partition: Service1
  delegate_to: localhost

- name: Destroy Service1 pool "Service1_pl" on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_pool:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    password: "{{BIGIPadminPassword}}"
    validate_certs: false
    state: absent
    name: Service1_pl
    partition: Service1
  delegate_to: localhost

- name: Destroy Service1 node {{application_server_name}}
  bigip_node:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    password: "{{BIGIPadminPassword}}"
    validate_certs: false
    state: absent
    partition: Service1
    name: 10.128.20.4
  delegate_to: localhost

- name: Remove Service1 partition "Service1"
  bigip_partition:
    name: Service1
    password: "{{BIGIPadminPassword}}"
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    validate_certs: false
    state: absent
  delegate_to: localhost

- name: Webhook Notification to Teams for Destruction of all Services on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  delegate_to: localhost
  uri:
    body: "{\"text\": \"All Services on BIG-IP {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com have been destroyed!\"}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: no
