# Destroy all Services in this solution

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    password: "{{BIGIPadminPassword}}"
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    validate_certs: no
  delegate_to: localhost

- name: Get Bigip Authentication Token from {{resource_group_name}}.{{location}}.cloudapp.azure.com
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{resource_group_name}}.{{location}}.cloudapp.azure.com/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigip_auth_token: "{{ bigip_auth_response.json.token.token }}"

- name: Destroy All Services in AS3 on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: DELETE
    status_code: 200
    url: "https://{{resource_group_name}}.{{location}}.cloudapp.azure.com/mgmt/shared/appsvcs/declare"
    validate_certs: no

- name: Destroy Service 2 from f5.http iApp on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_iapp_service:
    name: Service_2
    password: "{{BIGIPadminPassword}}"
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    state: absent
    user: "{{BIGIPadminUsername}}"
    validate_certs: no
  delegate_to: localhost

- name: Destroy Service 1 virtual server "service_1_vs" on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_virtual_server:
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: absent
    name: service_1_vs
    partition: Service1
  delegate_to: localhost

- name: Destroy Service 1 pool "service_1_pl" on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_pool:
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    password: "{{BIGIPadminPassword}}"
    validate_certs: false
    state: absent
    name: service_1_pl
    partition: Service1
  delegate_to: localhost

- name: Remove Service 1 partition "Service1"
  bigip_partition:
    name: Service1
    password: "{{BIGIPadminPassword}}"
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    validate_certs: false
    state: absent
  delegate_to: localhost

- name: Webhook Notification to Teams for Build
  delegate_to: localhost
  uri:
    body: "{\"text\": \"All AS3 Declarations on BIG-IP {{resource_group_name}}.{{location}}.cloudapp.azure.com were destroyed!\"}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: no
