---

- name: Setup provider
  set_fact:
    provider:
      server: "{{ bigiq_onboard_server }}"
      server_port: "{{ bigiq_onboard_server_port }}"
      user: "{{ bigiq_onboard_user }}"
      password: "{{ bigiq_onboard_password }}"
      validate_certs: "{{ bigiq_onboard_validate_certs }}"
      transport: "{{ bigiq_onboard_transport }}"

- name: Wait for BIG-IQ to be available
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/info/system"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
  register: status
  until: status is success and status.json.available|bool
  retries: 10
  delay: 6

- name: Test authentication
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/echo"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    user: "{{ bigiq_onboard_user }}"
    password: "{{ bigiq_onboard_password }}"
  register: status

- name: Check if system is setup
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/system/setup"
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    user: "{{ bigiq_onboard_user }}"
    password: "{{ bigiq_onboard_password }}"
  register: setup

- include_tasks: setup-main.yaml
  when: setup.json.isSystemSetup is not defined
