# Create or update a template deployment based on uris and template link
# for a single BIGIP with 3-nic's

---
-
  name: "Run F5 ARM Template to build a single BIG-IP with 1 NIC"
  azure_rm_deployment:
    client_id: "{{ clientId }}"
    location: "{{location}}"
    parameters:
      adminPassword:
        value: "{{BIGIPadminPassword}}"
      adminUsername:
        value: "{{BIGIPadminUsername}}"
      allowUsageAnalytics:
        value: "{{allowUsageAnalytics}}"
      bigIpVersion:
        value: "{{bigIpVersion}}"
      bigIqLicenseHost:
        value: "{{bigIqLicenseHost}}"
      bigIqLicensePassword:
        value: "{{bigIqLicensePassword}}"
      bigIqLicensePool:
        value: "{{bigIqLicensePool}}"
      bigIqLicenseUsername:
        value: "{{bigIqLicenseUsername}}"
      dnsLabel:
        value: "{{dnsLabel}}"
      imageName:
        value: "{{imageName}}"
      instanceName:
        value: "{{instanceName}}"
      instanceType:
        value: "{{instanceType}}"
      mgmtIpAddress:
        value: "{{mgmtIpAddress}}"
      mgmtSubnetName:
        value: "{{mgmtSubnetName}}"
      ntpServer:
        value: "{{ntpServer}}"
      restrictedSrcAddress:
        value: "{{restrictedSrcAddress}}"
      timeZone:
        value: "{{timeZone}}"
      vnetName:
        value: "{{vnetName}}"
      vnetResourceGroupName:
        value: "{{vnetResourceGroupName}}"
    resource_group_name: "{{resource_group_name}}"
    secret: "{{ servicePrincipalSecret }}"
    state: present
    subscription_id: "{{ subscriptionId }}"
    template_link: "{{bigip_template_link}}"
    tenant: "{{ tenantId }}"
-
  name: "Webhook Notification to Teams for Build of BIG-IP {{resource_group_name}}.{{location}}.cloudapp.azure.com"
  delegate_to: localhost
  uri:
    body:
      ? "@context"
      : "http://schema.org/extensions"
      ? "@type"
      : MessageCard
      potentialAction:
        -
          ? "@type"
          : OpenUri
          name: "BIG-IP "
          targets:
            -
              os: default
              uri: "https://{{resource_group_name}}.{{location}}.cloudapp.azure.com"
      text: "Click **BIG-IP Button** to be taken to the BIG-IP!"
      themeColor: 0072C6
      title: "New BIG-IP Environment Created in Resource Group {{resource_group_name}}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: false
