# Create or update a Application Virtual Machine

#- name: Create Server {{bigIqHost01}} Storage Account in {{resource_group_name}}
#  azure_rm_storageaccount:
#    tenant: "{{ tenantId }}"
#    client_id: "{{ clientId }}"
#    secret: "{{ servicePrincipalSecret }}"
#    subscription_id: "{{ subscriptionId }}"
#    location: "{{location}}"
#    resource_group: "{{resource_group_name}}"
#    name: "{{bigIqHost01_storage_account}}"
#    account_type: Premium_LRS

- name: Create Server {{bigIqHost01}} NIC_1 in {{resource_group_name}}
  azure_rm_networkinterface:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIqHost01}}_mgmt_nic"
    virtual_network: "{{virtual_network_name}}"
    subnet: "management"
    ip_configurations:
      - name: ipconfig1
        private_ip_allocation_method: Dynamic
        public_ip_address_name: "{{bigIqHost01}}-mgmt-pip0"
        primary: true

- name: Create Server {{bigIqHost01}} NIC_2 in {{resource_group_name}}
  azure_rm_networkinterface:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIqHost01}}_ext_nic"
    virtual_network: "{{virtual_network_name}}"
    subnet: "external"
    ip_configurations:
      - name: ipconfig1
        private_ip_allocation_method: Dynamic
        public_ip_address_name: "{{bigIqHost01}}-ext-pip0"

- name: Edit Security Group {{bigIqHost01}}_mgmt_nic in {{resource_group_name}} (Allow Management Access)
  azure_rm_securitygroup:
      tenant: "{{ tenantId }}"
      client_id: "{{ clientId }}"
      secret: "{{ servicePrincipalSecret }}"
      subscription_id: "{{ subscriptionId }}"
      resource_group: "{{resource_group_name}}"
      name: "{{bigIqHost01}}_mgmt_nic"
      purge_rules: yes
      rules:
          - name: 'AllowHTTPS'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: "443"
            access: Allow
            priority: 100
            direction: Inbound
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: 22
            access: Deny
            priority: 101
            direction: Inbound

- name: Edit Security Group {{bigIqHost01}}_ext_nic in {{resource_group_name}} (Deny All Access)
  azure_rm_securitygroup:
      tenant: "{{ tenantId }}"
      client_id: "{{ clientId }}"
      secret: "{{ servicePrincipalSecret }}"
      subscription_id: "{{ subscriptionId }}"
      resource_group: "{{resource_group_name}}"
      name: "{{bigIqHost01}}_ext_nic"
      purge_rules: yes
      rules:
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: 22
            access: Deny
            priority: 101
            direction: Inbound

- name: Create Server {{bigIqHost01}} Virtual Machine
  azure_rm_virtualmachine:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    location: "{{location}}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIqHost01}}"
    vm_size: Standard_D4s_v3
#    storage_account: "{{bigIqHost01_storage_account}}"
#    storage_container: "{{bigIqHost01}}001"
#    storage_blob: "{{bigIqHost01}}001.vhd"
    admin_username: "{{bigIqHost01Admin}}"
    admin_password: "{{bigIqHost01Password}}"
    network_interface_names:
      - "{{bigIqHost01}}_mgmt_nic"
      - "{{bigIqHost01}}_ext_nic"
    managed_disk_type: Premium_LRS
    image:
      offer: f5-big-iq
      publisher: f5-networks
      sku: f5-bigiq-virtual-edition-byol
      version: latest
    plan:
      name: f5-bigiq-virtual-edition-byol
      product: f5-big-iq
      publisher: f5-networks

- name: Execute VM Extension for Server {{bigIqHost01}}
  azure_rm_virtualmachine_extension:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    location: "{{location}}"
    name: Enable_Basic_Auth
    resource_group: "{{resource_group_name}}"
    virtual_machine_name: "{{bigIqHost01}}"
    publisher: Microsoft.Azure.Extensions
    virtual_machine_extension_type: CustomScript
    type_handler_version: 2.0
    settings: '{"commandToExecute": "set-basic-auth on"}'
    auto_upgrade_minor_version: true

- name: License {{bigIqHost01}}
  uri:
    url: "https://{{bigIqHost01Address}}/mgmt/tm/sys/license"
    method: POST
    validate_certs: no
    user: "{{ bigIqHost01Admin }}"
    password: "{{ bigIqHost01Password }}"
    body:
      command: "install"
      registrationKey: "{{ bigIqHost01License }}"
    body_format: json

- name: Webhook Notification to Teams for Build of Server {{bigIqHost01}}
  delegate_to: localhost
  uri:
    body: "{\"text\": \"Application Server {{bigIqHost01}} was created in Resource Group {{resource_group_name}}!\"}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: no
