# Create or update a Application Virtual Machine

#- name: Create Server {{bigIqHost01}} Storage Account in {{resource_group_name}}
#  azure_rm_storageaccount:
#    tenant: "{{ tenantId }}"
#    client_id: "{{ clientId }}"
#    secret: "{{ servicePrincipalSecret }}"
#    subscription_id: "{{ subscriptionId }}"
#    location: "{{location}}"
#    resource_group: "{{resource_group_name}}"
#    name: "{{bigIqHost01_storage_account}}"
#    account_type: Premium_LRS

- name: Create Server {{bigIqHost01}} NIC_1 in {{resource_group_name}}
  azure_rm_networkinterface:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIqHost01}}_mgmt_nic"
    virtual_network: "{{virtual_network_name}}"
    subnet: "management"
    ip_configurations:
      name: ipconfig1
      private_ip_allocation_method: Dynamic
      public_ip_address_name: "{{bigIqHost01}}-mgmt-pip0"
      primary: yes

- name: Create Server {{bigIqHost01}} NIC_2 in {{resource_group_name}}
  azure_rm_networkinterface:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIqHost01}}_ext_nic"
    virtual_network: "{{virtual_network_name}}"
    subnet: "external"
    ip_configurations:
      name: ipconfig1
      private_ip_allocation_method: Dynamic
#      public_ip_address_name: "{{bigIqHost01}}-external-pip0"

- name: Edit Security Group {{bigIqHost01}} in {{resource_group_name}} (Allow HTTP(S) Deny SSH)
  azure_rm_securitygroup:
      tenant: "{{ tenantId }}"
      client_id: "{{ clientId }}"
      secret: "{{ servicePrincipalSecret }}"
      subscription_id: "{{ subscriptionId }}"
      resource_group: "{{resource_group_name}}"
      name: "{{bigIqHost01}}"
      purge_rules: yes
      rules:
          - name: 'AllowHTTP'
            protocol: Tcp
            source_address_prefix: 'VirtualNetwork'
            destination_port_range: "80-84"
            access: Allow
            priority: 100
            direction: Inbound
          - name: 'AllowHTTPS'
            protocol: Tcp
            source_address_prefix: 'VirtualNetwork'
            destination_port_range: "443-444"
            access: Allow
            priority: 101
            direction: Inbound
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: 22
            access: Deny
            priority: 102
            direction: Inbound

- name: Create Server {{bigIqHost01}} Virtual Machine
  azure_rm_virtualmachine:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    location: "{{location}}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIqHost01}}"
    vm_size: Standard_D4s_v3
#    storage_account: "{{bigIqHost01_storage_account}}"
#    storage_container: "{{bigIqHost01}}001"
#    storage_blob: "{{bigIqHost01}}001.vhd"
    admin_username: "{{bigIqHost01Admin}}"
    admin_password: "{{bigIqHost01Password}}"
    network_interface_names:
      - "{{bigIqHost01}}_mgmt_nic"
      - "{{bigIqHost01}}_ext_nic"
    managed_disk_type: Premium_LRS
    image:
      offer: f5-big-iq
      publisher: f5-networks
      sku: f5-bigiq-virtual-edition-byol
      version: latest
    plan:
      name: f5-bigiq-virtual-edition-byol
      product: f5-big-iq
      publisher: f5-networks

- name: Webhook Notification to Teams for Build of Server {{bigIqHost01}}
  delegate_to: localhost
  uri:
    body: "{\"text\": \"Application Server {{bigIqHost01}} was created in Resource Group {{bigIqHost01}}!\"}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: no
