# Create an F5 BIG-IQ instance with 2 NIC's

- name: Create {{bigIq01}} Managemnet NIC in Resource Group {{resource_group_name}}
  azure_rm_networkinterface:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIq01}}_mgmt_nic"
    virtual_network: "{{virtual_network_name}}"
    subnet: "{{managemenet_subnet}}"
    ip_configurations:
      - name: ipconfig1
        private_ip_allocation_method: Dynamic
        public_ip_address_name: "{{bigIq01}}-mgmt-pip0"
        primary: true

- name: Create {{bigIq01}} Internal NIC in Resource Group {{resource_group_name}}
  azure_rm_networkinterface:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIq01}}_int_nic"
    virtual_network: "{{virtual_network_name}}"
    subnet: "{{internal_subnet}}"
    ip_configurations:
      - name: ipconfig1
        private_ip_allocation_method: Dynamic
        public_ip_address_name: "{{bigIq01}}-int-pip0"
  register: "bigIq01_int_nic_private"

- name: Edit {{bigIq01}}_mgmt_nic Security Group in {{resource_group_name}} (Allow HTTPS Access)
  azure_rm_securitygroup:
      tenant: "{{ tenantId }}"
      client_id: "{{ clientId }}"
      secret: "{{ servicePrincipalSecret }}"
      subscription_id: "{{ subscriptionId }}"
      resource_group: "{{resource_group_name}}"
      name: "{{bigIq01}}_mgmt_nic"
      purge_rules: yes
      rules:
          - name: 'AllowHTTPS'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: "443"
            access: Allow
            priority: 100
            direction: Inbound
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: 22
            access: Deny
            priority: 101
            direction: Inbound

- name: Edit {{bigIq01}}_int_nic Security Group in {{resource_group_name}} (Deny All External Access)
  azure_rm_securitygroup:
      tenant: "{{ tenantId }}"
      client_id: "{{ clientId }}"
      secret: "{{ servicePrincipalSecret }}"
      subscription_id: "{{ subscriptionId }}"
      resource_group: "{{resource_group_name}}"
      name: "{{bigIq01}}_ext_nic"
      purge_rules: yes
      rules:
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix: '{{restrictedSrcAddress}}'
            destination_port_range: 22
            access: Deny
            priority: 101
            direction: Inbound

- name: Create {{bigIq01}} Virtual Machine
  azure_rm_virtualmachine:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    location: "{{location}}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIq01}}"
    vm_size: Standard_D4s_v3
    admin_username: "{{bigIq01Admin}}"
    admin_password: "{{bigIq01Password}}"
    network_interface_names:
      - "{{bigIq01}}_mgmt_nic"
      - "{{bigIq01}}_int_nic"
    managed_disk_type: Premium_LRS
    image:
      offer: f5-big-iq
      publisher: f5-networks
      sku: f5-bigiq-virtual-edition-byol
      version: latest
    plan:
      name: f5-bigiq-virtual-edition-byol
      product: f5-big-iq
      publisher: f5-networks

- name: Gather {{bigIq01}}_mgmt_nic Facts
  azure_rm_publicipaddress:
    tenant: "{{ tenantId }}"
    client_id: "{{ clientId }}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    resource_group: "{{resource_group_name}}"
    name: "{{bigIq01}}-mgmt-pip0"
  register: "bigIq01_mgmt_nic_external"

- name: Assign {{bigIq01}}_mgmt_nic Fact
  set_fact:
    bigIq01_mgmt_pip: "{{ bigIq01_mgmt_nic_external.state.ip_address }}"

- name: Assign {{bigIq01}}_int_nic Fact
  set_fact:
    bigIq01_int_pri_ip: "{{ bigIq01_int_nic_private.state.ip_configuration.private_ip_address }}"

- debug:
    msg: Registered "{{ bigIq01_mgmt_nic_external.state.ip_address }}" as Management NIC External IP

- debug:
    msg: Registered "{{ bigIq01_int_nic_private.state.ip_configuration.private_ip_address }}" as Internal NIC Private IP

- pause:
    minutes: 10

- name: Webhook Notification to Teams for Build of {{bigIq01}}
  delegate_to: localhost
  uri:
    body:
      ? "@context"
      : "http://schema.org/extensions"
      ? "@type"
      : MessageCard
      potentialAction:
        -
          ? "@type"
          : OpenUri
          name: "BIG-IQ"
          targets:
            -
              os: default
              uri: "https://{{ bigIq01_mgmt_pip }}"
      text: "Click **BIG-IQ Button** to be taken to {{bigIq01}}!"
      themeColor: 0072C6
      title: "New BIG-IQ Created in Resource Group {{resource_group_name}}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: false
