# service_4 specific parameters

# use parent_parameters.yml for secure variables (ansible-vault)

#module parameters
serviceName: "Service4"
frontEnd: "10.128.10.29"
backEndMember1IP: "10.128.20.4"
backEndMember1Port: "83"
backEndMember2IP: "10.128.20.4"
backEndMember2Port: "84"
restrictedSrcAddress: "*"
