# Create or update a Service 2, f5.http iapp Build Simple Application

      - name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
        bigip_wait:
          timeout: 300
          password: "{{BIGIPadminPassword}}"
          server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
          user: "{{BIGIPadminUsername}}"
          validate_certs: no
        delegate_to: localhost

      - name: Create a pool
        bigip_pool:
            lb_method: "ratio-member"
            name: "service_2_pl"
            password: "{{ BIGIPadminPassword }}"
            server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
            slow_ramp_time: "120"
            user: "{{ BIGIPadminUsername }}"
            validate_certs: no
        delegate_to: localhost

      - name: Create node1
        bigip_node:
            host: "10.10.10.10"
            name: "node-1"
            password: "{{ BIGIPadminPassword }}"
            server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
            user: "{{ BIGIPadminUsername }}"
            validate_certs: no
        delegate_to: localhost

      - name: Add nodes to pool
        bigip_pool_member:
            description: "webserver-1"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: "{{ BIGIPadminPassword }}"
            pool: "service_2_pl"
            port: "80"
            server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
            user: "{{ BIGIPadminUsername }}"
            validate_certs: no
        delegate_to: localhost
        with_items:
            - host: "10.128.20.4"
              name: "node-1"

      - name: Create a VIP
        bigip_virtual_server:
            description: "foo-vip"
            destination: "10.128.10.21"
            password: "{{ BIGIPadminPassword }}"
            name: "service_2_vs"
            pool: "service_2_pl"
            port: "80"
            server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
            snat: "Automap"
            user: "{{ BIGIPadminUsername }}"
            all_profiles:
                - "http"
                - "clientssl"
            validate_certs: no
        delegate_to: localhost

      - name: Webhook Notification to Teams for Build
        delegate_to: localhost
        uri:
          body: { "@context": "http://schema.org/extensions", "@type": "MessageCard", "themeColor": "0072C6", "title": "Service 2 has been created on {{resource_group_name}}.{{location}}.cloudapp.azure.com", "text": "Click **Service 2 Button** to be taken to the Service 2 Application", "potentialAction": [{ "@type": "OpenUri", "name": "Service 2", "targets": [{ "os": "default", "uri": "https://{{resource_group_name}}1.{{location}}.cloudapp.azure.com" }] }] }
          body_format: json
          method: POST
          status_code: 200
          url: "{{teams_webhook}}"
          validate_certs: no
