# bigip_single_3_nic specific parameters

# use parent_parameters.yml for secure variables (ansible-vault)

#module parameters
allowUsageAnalytics: "Yes"
bigIpVersion: "latest"
bigip_template_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/standalone/3nic/existing-stack/bigiq/azuredeploy.json"
bigip_parameters_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/standalone/3nic/existing-stack/bigiq/azuredeploy.parameters.json"
customImage: "OPTIONAL"
dnsLabel: "{{instanceName}}-{{resource_group_name}}"
externalIpAddressRangeStart: "10.128.10.200"
externalSubnetName: "external"
imageName: "AllOneBootLocation"
instanceName: "{{BigIp_instance_name}}"
instanceType: "Standard_DS3_v2"
internalIpAddress: "10.128.20.200"
internalSubnetName: "internal"
mgmtIpAddress: "10.128.1.200"
mgmtSubnetName: "management"
ntpServer: "0.pool.ntp.org"
restrictedSrcAddress: "*"
timeZone: "UTC"
vnetName: "{{resource_group_name}}-virtual-network"
vnetResourceGroupName: "{{resource_group_name}}"
