{{instanceName}}.# Create or update a template deployment based on uris and template link
# for a cluster of BIGIP's

---
-
  name: "Run F5 ARM Template to build a cluster of BIG-IP's with 3 NIC's"
  azure_rm_deployment:
    client_id: "{{ clientId }}"
    location: "{{location}}"
    resource_group_name: "{{resource_group_name}}"
    secret: "{{ servicePrincipalSecret }}"
    state: present
    subscription_id: "{{ subscriptionId }}"
    template_link: "{{bigip_template_link}}"
    tenant: "{{ tenantId }}"
    parameters:
      adminPasswordOrKey:
        value: "{{BIGIPadminPassword}}"
      adminUsername:
        value: "{{BIGIPadminUsername}}"
#      additionalNicLocation:
#        value: "{{additionalNicLocation}}"
      allowUsageAnalytics:
        value: "{{allowUsageAnalytics}}"
      authenticationType:
        value: "password"
      bigIpVersion:
        value: "{{bigIpVersion}}"
      bigIqAddress:
        value: "{{bigIqLicenseHost}}"
      bigIqPassword:
        value: "{{bigIqLicensePassword}}"
      bigIqLicensePoolName:
        value: "{{bigIqLicensePool}}"
      bigIqLicenseSkuKeyword1:
        value: "{{bigIqLicenseSkuKeyword1}}"
      bigIqLicenseUnitOfMeasure:
        value: "{{bigIqLicenseUnitOfMeasure}}"
      bigIqUsername:
        value: "{{bigIqLicenseUsername}}"
      customImage:
        value: "{{customImage}}"
      clientId:
        value: "{{clientId}}"
      dnsLabel:
        value: "{{dnsLabel}}"
      externalIpAddressRangeStart:
        value: "{{externalIpAddressRangeStart}}"
      externalIpSelfAddressRangeStart:
        value: "{{externalIpSelfAddressRangeStart}}"
      externalSubnetName:
        value: "{{externalSubnetName}}"
      imageName:
        value: "{{imageName}}"
      instanceName:
        value: "{{instanceName}}"
      instanceType:
        value: "{{instanceType}}"
      internalIpAddressRangeStart:
        value: "{{internalIpAddressRangeStart}}"
      internalSubnetName:
        value: "{{internalSubnetName}}"
      managedRoutes:
        value: "{{managedRoutes}}"
      mgmtIpAddressRangeStart:
        value: "{{mgmtIpAddressRangeStart}}"
      mgmtSubnetName:
        value: "{{mgmtSubnetName}}"
      ntpServer:
        value: "{{ntpServer}}"
      numberOfExternalIps:
        value: 5
      numberOfAdditionalNics:
        value: "{{numberOfAdditionalNics}}"
      restrictedSrcAddress:
        value: "{{restrictedSrcAddress}}"
      servicePrincipalSecret:
        value: "{{servicePrincipalSecret}}"
      tenantId:
        value: "{{tenantId}}"
      timeZone:
        value: "{{timeZone}}"
      vnetName:
        value: "{{vnetName}}"
      vnetResourceGroupName:
        value: "{{vnetResourceGroupName}}"
-
  name: "Webhook Notification to Teams for Build of BIG-IP Cluster {{instanceName}}.{{resource_group_name}}-0.{{location}}.cloudapp.azure.com & {{instanceName}}.{{resource_group_name}}-1.{{location}}.cloudapp.azure.com"
  delegate_to: localhost
  uri:
    body:
      ? "@context"
      : "http://schema.org/extensions"
      ? "@type"
      : MessageCard
      potentialAction:
        -
          ? "@type"
          : OpenUri
          name: "BIG-IP 1"
          targets:
            -
              os: default
              uri: "https://{{instanceName}}-{{resource_group_name}}-0.{{location}}.cloudapp.azure.com"
        -
          ? "@type"
          : OpenUri
          name: "BIG-IP 2"
          targets:
            -
              os: default
              uri: "https://{{instanceName}}-{{resource_group_name}}-1.{{location}}.cloudapp.azure.com"
      text: "Click **BIG-IP Button** to be taken to a BIG-IP!"
      themeColor: 0072C6
      title: "New BIG-IP Environment Created in Resource Group {{resource_group_name}}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: false
