# Add a license pool to a BIG-IQ CM

- name: Get {{bigIq01}} Authentication Token
  delegate_to: localhost
  uri:
    body: '{"username":"{{bigIq01Admin}}","password":"{{bigIq01Password}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{ bigIq01_mgmt_pip }}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigIq01_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigIq01_auth_token: "{{ bigIq01_auth_response.json.token.token }}"

- name: Activate {{bigIq01_mgmt_pip}} License Pool
  uri:
    url: "https://{{bigIq01_mgmt_pip}}/mgmt/cm/shared/esmgmt/add-node"
    method: POST
    validate_certs: no
    headers:
      X-F5-Auth-Token: "{{ bigIq01_auth_token }}"
    body:
      regKey: "{{ {{ bigIqMSPRegKey }} }}"
      status: "ACTIVATING_AUTOMATIC"
      name: "{{ bigIqLicensePool }}"
    body_format: json


- name: Accept {{ bigIqMSPRegKey }} EULA
  uri:
    url: "https://{{bigIq01_mgmt_pip}}/mgmt/cm/shared/esmgmt/add-node"
    method: PATCH
    validate_certs: no
    headers:
      X-F5-Auth-Token: "{{ bigIq01_auth_token }}"
    body:
      status: "ACTIVATING_AUTOMATIC_EULA_ACCEPTED"
      eulaText: FILE IN FILE FOLDER
    body_format: json

- name: Webhook Notification to Teams for license {{ bigIqMSPRegKey }} activation
  delegate_to: localhost
  uri:
    body: "{\"text\": \"License Pool {{ bigIqMSPRegKey }} has been added into BIG-IQ {{ bigIq01_mgmt_pip }}\"}"
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: no
