# Onboard a BIG-IQ 2 NIC installation with CM Personality

- name: Verify {{bigIqDCD}} is available
  uri:
    url: "https://{{ bigIqDCD_mgmt_pip }}/info/system"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
    validate_certs: no
  register: bigIqDCD_status
  until: bigIqDCD_status.json.available == true
  retries: 10
  delay: 6

- name: Test {{bigIqDCD}} authentication
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/shared/echo"
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"

- name: License {{bigIqDCD}}
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/tm/sys/license"
    method: POST
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      command: "install"
      registrationKey: "{{ bigIqDCDLicense }}"
    body_format: json

- name: Set {{bigIqDCD}} Personality
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/cm/system/provisioning"
    method: POST
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      systemPersonality: "logging_node"
    body_format: json

- name: Execute {{bigIqDCD}} easy-setup
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/shared/system/easy-setup"
    method: PATCH
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      hostname: "{{bigIqDCD}}.iq"
    body_format: json

- name: Set {{bigIqDCD}} Master-Key
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/cm/shared/secure-storage/masterkey"
    method: POST
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      passphrase: "{{bigIqHostPassphrase}}"
    body_format: json

- name: Set {{bigIqDCD}} Admin Credentials
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/shared/authz/users"
    method: PUT
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      name: "{{ bigIqDCDAdmin }}"
      oldPassword: "{{ bigIqDCDPassword }}"
      password: "{{ bigIqDCDPassword }}"
      password2: "{{ bigIqDCDPassword }}"
      encryptedPassword: null
    body_format: json

#- name: Set {{bigIqDCD}} Root Credentials
#  uri:
#    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/shared/authn/root"
#    method: POST
#    validate_certs: no
#    user: "{{ bigIqDCDAdmin }}"
#    password: "{{ bigIqDCDPassword }}"
#    body:
#      oldPassword: "{{ oldPassword_root }}"
#      newPassword: "{{ bigIqDCDPassword }}"
#    body_format: json

- name: Close {{bigIqDCD}} Wizard
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/shared/system/setup"
    method: PATCH
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      isSystemSetup: true
    body_format: json

- name: Restart {{bigIqDCD}} Services
  uri:
    url: "https://{{bigIqDCD_mgmt_pip}}/mgmt/shared/failover-state"
    method: PATCH
    validate_certs: no
    user: "{{ bigIqDCDAdmin }}"
    password: "{{ bigIqDCDPassword }}"
    body:
      restart: true
    body_format: json
