# Create or update a Service 1, Imperative Build Simple Application
---
- bigip_wait:
    password: "{{BIGIPadminPassword}}"
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    timeout: 300
    user: "{{BIGIPadminUsername}}"
    validate_certs: false
  delegate_to: localhost
  name: "Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration"

- name: Create partition "Service1" using the default route domain
  bigip_partition:
    name: Service1
    password: "{{BIGIPadminPassword}}"
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    validate_certs: false
  delegate_to: localhost

- name: Create a pool on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_pool:
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    password: "{{BIGIPadminPassword}}"
    validate_certs: false
    state: present
    name: service_1_pl
    partition: Service1
    lb_method: least-connections-member
    slow_ramp_time: 120
  delegate_to: localhost

- name: Add a node on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_node:
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: present
    partition: Service1
    host: 10.128.20.4
    name: node_1
  delegate_to: localhost

- name: Add pool member to pool service_1_pl on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_pool_member:
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: present
    pool: service_1_pl
    partition: Service1
    host: 10.128.20.4
    port: 80
    description: web server
    connection_limit: 100
    rate_limit: 50
    ratio: 2
  delegate_to: localhost

- name: "Edit Security Group {{resource_group_name}}-ext-nsg in {{resource_group_name}}"
  azure_rm_securitygroup:
    client_id: "{{ clientId }}"
    name: "{{resource_group_name}}-ext-nsg"
    purge_rules: false
    resource_group: "{{resource_group_name}}"
    rules:
      -
        access: Allow
        destination_port_range: 80
        direction: Inbound
        name: AllowHTTP
        priority: 100
        protocol: Tcp
        source_address_prefix: "{{restrictedSrcAddress}}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    tenant: "{{ tenantId }}"

- name: Add virtual server for Service 1 on {{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_virtual_server:
    server: "{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: present
    partition: Service1
    name: service_1_vs
    destination: 10.128.10.26
    port: 80
    pool: service_1_pl
    snat: Automap
    description: Test Virtual Server
    profiles:
      - http

- name: "Webhook Notification to Teams for Build"
  uri:
    body: { "@context": "http://schema.org/extensions", "@type": "MessageCard", "themeColor": "0072C6", "title": "Service 1 has been created on {{resource_group_name}}.{{location}}.cloudapp.azure.com", "text": "Click **Service 1 Button** to be taken to the Service 1 Application", "potentialAction": [{ "@type": "OpenUri", "name": "Service 1", "targets": [{ "os": "default", "uri": "http://{{resource_group_name}}0.{{location}}.cloudapp.azure.com" }] }] }
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: false
