# Create or update Service 1; Imperative Build Simple HTTP Application
---
- bigip_wait:
    password: "{{BIGIPadminPassword}}"
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    timeout: 300
    user: "{{BIGIPadminUsername}}"
    validate_certs: false
  delegate_to: localhost
  name: "Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration"

- name: Create partition {{ serviceName }} using the default route domain
  bigip_partition:
    name: "{{ serviceName }}"
    password: "{{BIGIPadminPassword}}"
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    validate_certs: false
    state: present
  delegate_to: localhost

- name: Create pool {{ serviceName }}_pl on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_pool:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{BIGIPadminUsername}}"
    password: "{{BIGIPadminPassword}}"
    validate_certs: false
    state: present
    name: "{{ serviceName }}_pl"
    partition: "{{ serviceName }}"
    lb_method: least-connections-member
    slow_ramp_time: 120
    monitor_type: single
    monitors:
      - /Common/http
  delegate_to: localhost

- name: Add pool member {{ backEndMember1IP }} to pool {{ serviceName }}_pl on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_pool_member:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: present
    pool: "{{ serviceName }}_pl"
    partition: "{{ serviceName }}"
    host: "{{ backEndMember1IP }}"
    port: "{{ backEndMember1Port }}"
    description: web server
    connection_limit: 100
    rate_limit: 50
    ratio: 2
  delegate_to: localhost

- name: Add virtual server "{{ serviceName }}_vs" for {{ serviceName }} on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com
  bigip_virtual_server:
    server: "{{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com"
    user: "{{ BIGIPadminUsername }}"
    password: "{{ BIGIPadminPassword }}"
    validate_certs: false
    state: present
    partition: "{{ serviceName }}"
    name: "{{ serviceName }}_vs"
    destination: "{{ frontEnd }}"
    port: "{{ frontEndClear }}"
    pool: "{{ serviceName }}_pl"
    snat: Automap
    description: "{{ serviceName }}"
    profiles:
      - http

- name: "Edit Security Group {{resource_group_name}}-ext-nsg in {{resource_group_name}}"
  azure_rm_securitygroup:
    client_id: "{{ clientId }}"
    name: "{{resource_group_name}}-ext-nsg"
    purge_rules: false
    resource_group: "{{resource_group_name}}"
    rules:
      -
        access: Allow
        destination_port_range: 80
        direction: Inbound
        name: AllowHTTP
        priority: 100
        protocol: Tcp
        source_address_prefix: "{{restrictedSrcAddress}}"
    secret: "{{ servicePrincipalSecret }}"
    subscription_id: "{{ subscriptionId }}"
    tenant: "{{ tenantId }}"

- name: Webhook Notification to Teams for Build of {{ serviceName }}
  uri:
    body: { "@context": "http://schema.org/extensions", "@type": "MessageCard", "themeColor": "0072C6", "title": "{{ serviceName }} has been created on {{instanceName}}-{{resource_group_name}}.{{location}}.cloudapp.azure.com", "text": "Click **{{ serviceName }} Button** to be taken to the {{ serviceName }} Application", "potentialAction": [{ "@type": "OpenUri", "name": "{{ serviceName }}", "targets": [{ "os": "default", "uri": "http://{{resource_group_name}}0.{{location}}.cloudapp.azure.com" }] }] }
    body_format: json
    method: POST
    status_code: 200
    url: "{{teams_webhook}}"
    validate_certs: false
